apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
    - name: http-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer