apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-service
    spec:
      containers:
      - name: nginx
        image: s_nginx:test
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80

    - name: https-port
      port: 443
      targetPort: 443
  selector:
    app: nginx-service
  type: LoadBalancer