apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-service
    spec:
      containers:
      - name: nginx
        image: s_nginx:test
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          protocol: TCP