apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 20020
        - containerPort: 20021
        - containerPort: 20022
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
    - name: ftps-data
      port: 20
      targetPort: 20
    - name: ftps-connection
      port: 21
      targetPort: 21
    - name: ftps-data0
      port: 20020
      targetPort: 20020
    - name: ftps-data1
      port: 20021
      targetPort: 20021
    - name: ftps-data2
      port: 20022
      targetPort: 20022
  selector:
    app: ftps
  type: LoadBalancer