apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
    - name: ftps-port
      port: 21
      targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer